// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, userID int64) (Order, error)
	CreateOrderProduct(ctx context.Context, arg CreateOrderProductParams) (OrderProduct, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProduct(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetOrder(ctx context.Context, id int64) (Order, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListOrderProducts(ctx context.Context, arg ListOrderProductsParams) ([]OrderProduct, error)
	ListOrders(ctx context.Context, userID int64) ([]Order, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
